config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :entry_types

  resources :expenses

  resources :expense_types

  get "daily_collections/(:date)" => "daily_collections#index",
        :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
        :as => "daily_collections_date"

  resources :daily_collections

  resources :loans


  resources :customers

  get "dashboard/(:date)" => "dashboard#index",
      :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
      :as => "dashboard_date"

  get "dashboard/report" => "dashboard#report"

  resources :dashboard, only: [:index, :create]

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'visitors#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/views/visitors/index.html.erb
<h3>Welcome <strong><%= current_user.username %></strong></h3>

<div class="row">
  <div class="col-sm-8 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Customer Details</h3>
        <p>View customer lists. In the new page you can edit/delete customer</p>
        <p><%= link_to 'View Customer', customers_path, class: "btn btn-default", role: "button" %>
          <%= link_to 'Add New Customer', new_customer_path, class: "btn btn-default", role: "button" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-8 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Loan Details</h3>
        <p>View customer lists. In the new page you can edit/delete customer</p>
        <p><%= link_to 'View Party list', loans_path, class: "btn btn-default", role: "button" %>
          <%= link_to 'Add New Party', new_loan_path, class: "btn btn-default", role: "button" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-8 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Collection Details</h3>
        <p>View customer lists. In the new page you can edit/delete customer</p>
        <p><%= link_to "View Today's Collections", daily_collections_date_path(Date.today), class: "btn btn-default", role: "button" %>
          <%= link_to 'Add New Collection', new_daily_collection_path, class: "btn btn-default", role: "button" %></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Expenses and Incomes Dashboard</h3>
        <p>View daily expenses in this tab</p>
        <p><%= link_to "View Today's Transactions", dashboard_date_path(Date.today), class: "btn btn-default", role: "button" %>
          <%= link_to 'View date wise transations', dashboard_index_path, class: "btn btn-default", role: "button" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-8 col-md-4">
    <div class="thumbnail">
      <div class="caption">
        <h3>Generate Report</h3>
        <p>View customer lists. In the new page you can edit/delete customer</p>
        <p><%= link_to 'Generate Next Day Report',  daily_collections_date_path(:date => Date.today+1, format: :pdf), class: "btn btn-default", role: "button" %>
          <%= link_to "Generate Today's Day Report",  daily_collections_date_path(:date => Date.today, format: :pdf), class: "btn btn-default", role: "button" %></p>
      </div>
    </div>
  </div>
</div>