config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :entry_types

  resources :expenses

  resources :expense_types

  get "daily_collections/(:date)" => "daily_collections#index",
        :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
        :as => "daily_collections_date"

  resources :daily_collections

  resources :loans


  resources :customers

  get "dashboard/(:date)" => "dashboard#index",
      :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
      :as => "dashboard_date"

  get "dashboard/report" => "dashboard#report"

  resources :dashboard, only: [:index, :create]

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'visitors#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :entry_type
  belongs_to :user

  scope :incomes, lambda {
                  joins(:entry_type).where('entry_types.income = true')
                }
  scope :expenses, lambda {
                   joins(:entry_type).where('entry_types.income = false')
                 }

  scope :by_date, ->(date) { where(:entry_date => date) }

  scope :desc, -> { order created_at: :desc }

  def type
    entry_type
  end

  def set_name
    self.name = type.name if name.blank? || name.nil?
  end

  def self.total_amount
    all.map(&:amount).reduce(:+) || 0
  end
end

app/models/entry_type.rb
class EntryType < ActiveRecord::Base
  has_many :entries, dependent: :destroy


  scope :incomes, -> { where(income: true) }
  scope :expenses, -> { where(income: false) }

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :load_entry_type, only: [:new, :show, :edit]

  respond_to :html

  def create
    Entry.create(entry_params)
    parsed_date   = Date.strptime(params[:entry][:entry_date],'%d-%m-%Y')
    redirect_to dashboard_date_path(parsed_date)
  end

  def destroy
    entry_record = Entry.find_by(id: params[:id])
    entry_record.try(:destroy)
    redirect_to dashboard_date_path(entry_record.entry_date), status: 303
  end

  def index
    @entries = Entry.all
    respond_with(@entries)
  end

  def show
    respond_with(@entry)
  end

  def new
    @entry = Entry.new
    respond_with(@entry)
  end

  def edit
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

  def load_entry_type
    @entry_types = EntryType.all
    @users = User.all
  end

    def entry_params
      params.require(:entry).permit(:entry_type_id, :user_id, :amount, :entry_date)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.erb
<%= form_for(@entry, html: {class: 'form col-md-6 col-md-offset-3'}) do |f| %>
    <% if @entry.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

          <ul>
            <% @entry.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="fieldset">
      <div class="form-group">
        <%= f.label :entry_type %><br>
        <%= collection_select(:entry, :entry_type_id, @entry_types, :id, :name, class: 'form-control')%>
      </div>
      <div class="form-group">
        <%= f.label :user_id %><br>
        <%= collection_select(:entry, :user_id, @users, :id, :username, class: 'form-control')%>
      </div>
      <div class="form-group">
        <%= f.label :amount %><br>
        <%= f.text_field :amount, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :entry_date %><br>
        <%= f.text_field :entry_date, :class => 'datepicker', :value => Date.today.strftime('%d-%m-%Y') %><br/>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Listing entries</h1>

<div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Entry type</th>
      <th>User</th>
      <th>Amount</th>
      <th>Entry date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.entry_type.name %></td>
        <td><%= entry.user.username %></td>
        <td><%= entry.amount %></td>
        <td><%= entry.entry_date %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Entry type:</strong>
  <%= @entry.entry_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @entry.user %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @entry.amount %>
</p>

<p>
  <strong>Entry date:</strong>
  <%= @entry.entry_date %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>