config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :entry_types

  resources :expenses

  resources :expense_types

  get "daily_collections/(:date)" => "daily_collections#index",
        :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
        :as => "daily_collections_date"

  resources :daily_collections

  resources :loans


  resources :customers

  get "dashboard/(:date)" => "dashboard#index",
      :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
      :as => "dashboard_date"

  get "dashboard/report" => "dashboard#report"

  resources :dashboard, only: [:index, :create]

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'visitors#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/controllers/entry_types_controller.rb
class EntryTypesController < ApplicationController
  before_action :set_entry_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @entry_types = EntryType.all
    respond_with(@entry_types)
  end

  def show
    respond_with(@entry_type)
  end

  def new
    @entry_type = EntryType.new
    respond_with(@entry_type)
  end

  def edit
  end

  def create
    @entry_type = EntryType.new(entry_type_params)
    @entry_type.save
    redirect_to entry_types_path
  end

  def update
    @entry_type.update(entry_type_params)
    redirect_to entry_types_path
  end

  def destroy
    @entry_type.destroy
    redirect_to entry_types_path
  end

  private
    def set_entry_type
      @entry_type = EntryType.find(params[:id])
    end

    def entry_type_params
      params.require(:entry_type).permit(:name, :income)
    end
end

app/helpers/entry_types_helper.rb
module EntryTypesHelper
end

app/views/entry_types/_form.html.erb
<%= form_for(@entry_type, html: { class: 'form col-md-6 col-md-offset-3' }) do |f| %>
  <% if @entry_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry_type.errors.count, "error") %> prohibited this entry_type from being saved:</h2>

      <ul>
      <% @entry_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="fieldset">
      <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name , required: true%>
  </div>
      <div class="form-group">
    <%= f.label :income %><br>
    <%= f.check_box :income %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-info" %>
  </div>
        </div>
<% end %>

app/views/entry_types/edit.html.erb
<h1>Editing entry_type</h1>

<%= render 'form' %>

<%= link_to 'Back', entry_types_path, class: "btn btn-info" %>

app/views/entry_types/index.html.erb
<h1>Expense & Income Types</h1>
<div class="table-responsive">
  <table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Income</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entry_types.each do |entry_type| %>
      <tr>
        <td><%= entry_type.name %></td>
        <td><%= entry_type.income %></td>
        <td><%= link_to 'Edit', edit_entry_type_path(entry_type), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', entry_type, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Entry type', new_entry_type_path, class: "btn btn-info" %>

app/views/entry_types/new.html.erb
<h1>New entry_type</h1>

<%= render 'form' %>

<%= link_to 'Back', entry_types_path, class: "btn btn-info" %>

app/views/entry_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry_type.name %>
</p>

<p>
  <strong>Income:</strong>
  <%= @entry_type.income %>
</p>

<%= link_to 'Edit', edit_entry_type_path(@entry_type) %> |
<%= link_to 'Back', entry_types_path %>