config/routes.rb
Rails.application.routes.draw do
  resources :entries

  resources :entry_types

  resources :expenses

  resources :expense_types

  get "daily_collections/(:date)" => "daily_collections#index",
        :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
        :as => "daily_collections_date"

  resources :daily_collections

  resources :loans


  resources :customers

  get "dashboard/(:date)" => "dashboard#index",
      :constraints => { :date => /\d{4}-\d{2}-\d{2}/ },
      :as => "dashboard_date"

  get "dashboard/report" => "dashboard#report"

  resources :dashboard, only: [:index, :create]

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'visitors#index'
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/loan.rb
class Loan < ActiveRecord::Base
  extend Enumerize
  belongs_to :customer
  has_many :daily_collections, dependent: :destroy

  paginates_per 20

  default_scope { order(order_no: :asc) }

  before_save :auto_increment
  before_create :auto_increment
  before_save  :update_balance
  before_create :update_balance

  enumerize :loan_type,
            in: {Weekly: 1,
                 Daily: 2
            }, scope: true

  scope :weekly, -> { with_loan_type :Weekly }
  scope :daily, -> { with_loan_type :Daily }

  scope :active, -> { where(:active_status => true) }
  scope :inactive, -> { where(:active_status => false) }

  scope :customer_name, ->(name) { joins(:customer).where('lower(customers.name) like ?', "%#{name.downcase}%") }

  enumerize :vasool_day,
            in: {Sunday: 1,
                 Monday: 2,
                 Tuesday: 3,
                 Wednesday: 4,
                 Thursday: 5,
                 Friday: 6,
                 Saturday: 7
            }, scope: true

  scope :sunday, -> { with_vasool_day :Sunday }
  scope :monday, -> { with_vasool_day :Monday }
  scope :tuesday, -> { with_vasool_day :Tuesday }
  scope :wednesday, -> { with_vasool_day :Wednesday }
  scope :thursday, -> { with_vasool_day :Thursday }
  scope :friday, -> { with_vasool_day :Friday }
  scope :saturday, -> { with_vasool_day :Saturday }


  def self.search_name_day(query, day)
    customer_name(query).send(day)
  end

  def self.search_name(query)

    customer_name(query)
  end

  def update_balance_amount(balance)
    paid_amount = loan_amount - balance
    update(:balance_amount => balance, :paid_amount => paid_amount)
  end

  def calculate_weeks
    days = (Date.today - given_date).to_i
    days/7
  end

  def due_in_weeks
    installments - calculate_weeks
  end

  def self.total_paid(date)
    where(:given_date => date).map(&:given_amount).reduce(:+) || 0
  end


  def auto_increment
    loan = Loan.find_by_order_no(order_no)
    if loan && loan!=self
      @loan_all = Loan.where("order_no >= #{self.order_no}")
      @loan_all.each {|loan| loan.update_attribute(:order_no, loan.order_no+1)}
    end
  end

  def update_balance
    self.balance_amount = self.loan_amount - self.paid_amount
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
  before_action :load_customers, only: [:new, :show, :edit]

  respond_to :html

  def index
      if params[:active]
        load_loans('inactive')
      else
        load_loans('active')
      end
    respond_with(@loans)
  end

  def show
    respond_with(@loan) do |format|
      format.pdf do
        pdf = Report::LoanPaidReport.new.print_report(@loan)
        send_data pdf.render, filename: "#{@loan.customer.name_location}_loan_report.pdf", type: 'application/pdf'
      end
      format.html
    end
  end

  def new
    @loan = Loan.new
    @loan.order_no = Loan.last.nil? ? 1 : Loan.last.order_no.to_i + 1
    respond_with(@loan)
  end

  def edit
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.save
    redirect_to loans_path
  end

  def update
    @loan.update(loan_params)
    redirect_to loans_path
  end

  def destroy
    @loan.update_columns(:active_status => false)
    redirect_to customers_path
  end

  private

    def load_loans(active_status)
      if !params[:search_name].blank? && params[:loan] && !params[:loan][:search_day].blank?
        @loans = Loan.search_name_day(params[:search_name], params[:loan][:search_day]).page(params[:page]).send(active_status)
      elsif !params[:search_name].blank?
        @loans = Loan.search_name(params[:search_name]).page(params[:page]).send(active_status)
      elsif params[:loan] && !params[:loan][:search_day].blank?
        @loans = Loan.send(params[:loan][:search_day]).page(params[:page]).send(active_status)
      else
        @loans = Loan.all.page(params[:page]).send(active_status)
      end
    end

    def set_loan
      @loan = Loan.find(params[:id])
    end

    def load_customers
      @customers = Customer.all
    end



    def loan_params
      params.require(:loan).permit(:customer_id, :order_no, :loan_type, :vasool_day, :given_date, :loan_amount, :given_amount, :installment_amount, :installments, :paid_amount, :balance_amount, :active_status)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
  def check_for_value(row_id)
    row_id == nil ? :blank : row_id.value
  end

  def check_for_params(params)
    params == nil ? :blank : params[:search_day]
  end
end

app/views/loans/_form.html.erb
<%= form_for(@loan, html: { class: 'form col-md-6 col-md-offset-3' }) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="fieldset">
    <div class="form-group">
      <%= f.label :customer_id %>
      <%= collection_select(:loan, :customer_id, @customers, :id, :name_location, class: 'form-control', required: true)%>
    </div>
  <div class="form-group">
    <%= f.label :order_no %><br>
    <%= f.number_field :order_no, class: 'form-control' %>
  </div>
    <div class="form-group">
      <%= f.label :collection_day %>
      <%= select(:loan,
                 :vasool_day,
                 Loan.vasool_day.values.map { |x| [x, Loan.vasool_day.values.index(x) + 1] },
                 { :include_blank => "-Any-", :selected => check_for_value(@loan.vasool_day) }, { :class => 'form-control', required: true } )%>
    </div>
  <div class="form-group">
    <%= f.label :given_date %><br>
    <%= f.text_field :given_date, :class => 'datepicker', :value => Date.today.strftime('%d-%m-%Y') %>
  </div>
  <div class="form-group">
    <%= f.label :loan_amount %> (Customer need to pay)<br>
    <%= f.text_field :loan_amount, class: 'form-control', required: true%>
  </div>
  <div class="form-group">
    <%= f.label :given_amount %> (Given amount after reducing interest)<br>
    <%= f.text_field :given_amount, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :installment_amount %> (Daily pay amount )<br>
    <%= f.text_field :installment_amount, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :installments %> (How many weeks need to complete the loan)<br>
    <%= f.number_field :installments, class: 'form-control', required: true %>
  </div>
  <div class="form-group">
    <%= f.label :paid_amount %><br>
    <%= f.text_field :paid_amount, class: 'form-control' %>
  </div>
      <div class="col-sm-offset-2 col-sm-10">
        <div class="form-group">
          <%= f.label :active_status %>
          <%= f.check_box :active_status %>
        </div>
        </div>
      </div>
  <div class="actions">
    <%= f.submit  class: "btn btn-default" %>
  </div>
        </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path , class: "btn btn-info"%>

app/views/loans/index.html.erb
<h1>Parties List</h1>
<br/>

<%= form_tag(loans_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search_name, params[:search_name], placeholder: "Search Customers with Name" %>
    <%= select('loan','search_day',
               Loan.vasool_day.values.map { |x| [x, Loan.vasool_day.values.index(x) + 1, x.downcase] },
               { :include_blank => "-All-", :selected => check_for_params(params[:loan]) }, {} )%>
    <%= submit_tag "Sort by Collection Day", :name => nil, class: "btn btn-info" %>
<% end %>

<%= form_tag(loans_path, :method => "get", id: "search-form", html: { class: 'form col-md-6 col-md-offset-3' }) do %>
    <%= hidden_field_tag :active %>
    <%= submit_tag "View Old Parties", :name => nil, class: "btn btn-default" %>
<% end %>
<div class="row">
  <div class="col-xs-12 col-md-8"><%= paginate @loans , :theme => 'twitter-bootstrap-3'%></div>
  <div class="col-xs-6 col-md-4">Total Loans = <%= @loans.total_count%></div>
</div>

<div class="table-responsive">
  <table class="table table-bordered">
  <thead>
    <tr>
      <th>Customer</th>
      <th>Order no</th>
      <th>Collection day</th>
      <th>Given date</th>
      <th>Loan amount</th>
      <th>Given amount</th>
      <th>Installment amount</th>
      <th>Installments</th>
      <th>Paid amount</th>
      <th>Balance amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
        <td><b></b><%= link_to loan.customer.name_location, loan %></b></td>
        <td><%= loan.order_no %></td>

        <td><%= loan.vasool_day %></td>
        <td><%= loan.given_date %></td>
        <td><%= loan.loan_amount %></td>
        <td><%= loan.given_amount %></td>
        <td><%= loan.installment_amount %></td>
        <td><%= loan.installments %></td>
        <td><%= loan.paid_amount %></td>
        <td><%= loan.balance_amount %></td>
        <td><%= link_to 'Show', loan %></td>
        <td><%= link_to 'Edit', edit_loan_path(loan), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>

<div class="row">
  <div class="col-xs-12 col-md-8"><%= paginate @loans , :theme => 'twitter-bootstrap-3'%></div>
  <div class="col-xs-6 col-md-4"><%= link_to 'New Loan', new_loan_path, class: "btn btn-info" %></div>
</div>

app/views/loans/new.html.erb
<h1>New loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path, class: "btn btn-info" %>

app/views/loans/show.html.erb
<h2>Collection Date wise List</h2>
<br/>
<div class="row">
  <div class="col-md-6"></div>
  <div class="col-md-6"><%= link_to 'Back', loans_path, class: "btn btn-info" %>&nbsp;
    <%= link_to 'Print Report', loan_path(@loan, format: :pdf), class: "btn btn-info" %></div>
</div>
<div class="row">
  <div class="col-sm-3">
    <table>
      <tbody>
      <tr>
        <th>Customer Name:
        </td>
        <td>&nbsp;<%= @loan.customer.name_location %></td>
      </tr>
      <tr>
        <th>Loan Given date:
        </td>
        <td>&nbsp;<%= date_format_view(@loan.given_date) %></td>
      </tr>
      <tr>
        <th>Loan Amount:
        </td>
        <td>&nbsp;<%= @loan.loan_amount %></td>
      </tr>
      <tr>
        <th>Loan Paid Amount:
        </td>
        <td>&nbsp;<%= @loan.paid_amount %></td>
      </tr>
      <tr>
        <th>Balance Amount:
        </td>
        <td>&nbsp;<%= @loan.balance_amount %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>
<br/>
<div class="col-sm-3">
  <table class="table table-bordered table-stripped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Amount</th>
    </tr>
    </thead>

    <tbody>
    <% @loan.daily_collections.each do |loan| %>
        <tr>
          <td><%= loan.date_with_name %></td>
          <td><%= loan.amount %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>